#! /bin/bash

rm -rf test* Py_vs_pt.dat yptphi_Prest_all_particles.dat
g++ -fopenmp -o test src/*.cpp -lm -lgsl -lgslcblas
echo "After freezeout code is compiled sucessfully"

DataArray=("lower_mult_proxy_cut6.27975upper_mult_proxy_cut12.9697Shear_to_S_ratio0.08"
            "lower_mult_proxy_cut12.9697upper_mult_proxy_cut24.3598Shear_to_S_ratio0.08"
            "lower_mult_proxy_cut24.3498upper_mult_proxy_cut42.1198Shear_to_S_ratio0.08"
            "lower_mult_proxy_cut42.1198upper_mult_proxy_cut68.1697Shear_to_S_ratio0.08"
             "lower_mult_proxy_cut68.1697upper_mult_proxy_cut105.19Shear_to_S_ratio0.08"
              "lower_mult_proxy_cut105.19upper_mult_proxy_cut156.38Shear_to_S_ratio0.08"
              "lower_mult_proxy_cut156.38upper_mult_proxy_cut228.56Shear_to_S_ratio0.08"
              "lower_mult_proxy_cut228.56upper_mult_proxy_cut364.84Shear_to_S_ratio0.08")

for i in ${!DataArray[@]}; do
  ./test ../ForKoustav/${DataArray[$i]}/surface.dat my_particles.dat 
  mv Py_vs_pt.dat yptphi_Prest_all_particles.dat ../ForKoustav/${DataArray[$i]}/

done



#./test $1  my_particles.dat 
